name: BuildAndTest

on: [push]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1.1.4
        with:
          nim-version: "1.6.4"
      - run: "nimble build -y"
      - run: "nimble test -y"
